### ISSUE TITLE
Collection/showcase images are incorrect

### ISSUE THREAD

**Issue by DrKain** [After-the-End-of-All-Things/game#181]
Similar to #153 the tileset is offset by -1 meaning the wrong items are displayed on the profile showcase and collection list.

![firefox_0v3gWV4Nnm](https://github.com/After-the-End-of-All-Things/game/assets/5300315/e39b6a2a-5359-43be-9e87-3308938c0f59)
![firefox_S1jvqM42cO](https://github.com/After-the-End-of-All-Things/game/assets/5300315/e31bbbde-3697-439b-9181-512df3dedb9f)

**Comment by DrKain** [comment]
Possibly caused by https://github.com/After-the-End-of-All-Things/game/commit/ff4ac7619cf43d4e4ca40ffeee5ac478bcb6f54c ?

**Comment by seiyria** [comment]
Can you clear your cache and let me know if this issue persists?

**Comment by DrKain** [comment]
Ah!, displayed as normal now. I should have tried that first, sorry
