### ISSUE TITLE
prevent interact box with inventory items at bottom of screen from getting clipped

### ISSUE THREAD

**Issue by sarimash** [After-the-End-of-All-Things/game#82]
![image](https://github.com/After-the-End-of-All-Things/game/assets/6930354/8a6e6b49-b62f-4d5d-b9be-abce33e5b70e)

Should probably bump the interact dialog above the cursor instead of below, if the dialog can not fully display

**Comment by seiyria** [comment]
fixed a while ago but never closed the issue
